version: 2
jobs:
  build:
    docker:
      - image: selenium/hub:4.16.1-20231219
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Build images of services declared in docker-compose.yml
          command: docker-compose build

      # Run npm install
      - run:
          name: Install Dependencies
          command: npm install

      # Continue with your existing steps
      - run:
          name: Start Selenium Grid
          command: docker-compose -f docker-compose.yml up -d
      - run:
          name: Update npm
          command: npm update
      - run:
          name: Run Tests
          command: npm run test-cucumber @otto-run-this  # or whatever your test command is
      - run:
          name: Stop Selenium Grid
          command: docker-compose -f docker-compose.yml down
