name: Run Playwright Tests and Generate Allure Report

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install browsers
      run: npx playwright install

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run Playwright tests
      run: npx playwright test
      env:
        PW_BROWSER: chromium

    - name: Install Allure Command Line
      run: |
        npm install -g allure-commandline

    - name: Create allure-results directory
      run: mkdir allure-results

    - name: Check allure-results directory
      run: ls -l allure-results
      
    - name: Generate Allure Report
      run: |
        allure generate --clean
        allure open --port 8080

    - name: Upload Allure Report
      uses: actions/upload-artifact@v2
      with:
        name: allure-report
        path: allure-report