name: Run Playwright Tests and Generate Allure Report

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install browsers
      run: npx playwright install

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run Playwright tests
      run: npx playwright test
      env:
        PW_BROWSER: chromium

    - name: Generate Allure Report
      run: |
        npx allure generate --clean
        npx allure open --port 8080
